# Form implementation generated from reading ui file 'C:\Users\serge\OneDrive\Рабочий стол\учеба\4 сем\это база\интерфейс\financialReport.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_financialReport(object):
    def setupUi(self, financialReport):
        financialReport.setObjectName("financialReport")
        financialReport.resize(400, 126)
        self.verticalLayout = QtWidgets.QVBoxLayout(financialReport)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=financialReport)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.inputYear = QtWidgets.QLineEdit(parent=financialReport)
        self.inputYear.setObjectName("inputYear")
        self.verticalLayout.addWidget(self.inputYear)
        self.buttonNext = QtWidgets.QPushButton(parent=financialReport)
        self.buttonNext.setObjectName("buttonNext")
        self.verticalLayout.addWidget(self.buttonNext)

        self.retranslateUi(financialReport)
        QtCore.QMetaObject.connectSlotsByName(financialReport)

    def retranslateUi(self, financialReport):
        _translate = QtCore.QCoreApplication.translate
        financialReport.setWindowTitle(_translate("financialReport", "Финансовый отчет"))
        self.label.setText(_translate("financialReport", "Введите год, за который хотите получить финаносвый отчет:"))
        self.buttonNext.setText(_translate("financialReport", "Получить"))
